<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Xc thc OTP_otpvalue</name>
   <tag></tag>
   <elementGuidId>d1444aa7-8d77-4181-9b16-42247bb28f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#otpvalue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otpvalue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập mã OTP&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1470d327-d25b-4341-9f56-7f231b115bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9033f758-ae83-4ad4-b2b8-bc78182e52be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-label-change input-has-clear text-center</value>
      <webElementGuid>2a25c4b8-1861-4abc-a73a-fdc87aec2c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otpvalue</value>
      <webElementGuid>f4780cd8-d1d6-45c2-a8e7-1b44ec0978b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otpvalue</value>
      <webElementGuid>e24cb073-e77c-44e1-8758-98a9d01f68fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mã OTP</value>
      <webElementGuid>25f94752-783c-4188-814d-51a8b7181d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>fe77b8e3-9a0f-4f07-a692-a4909243a44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ab2e953b-39f2-43d1-ae59-fe62ba4a137e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>25e67f48-ea6e-4a64-b009-38d5fdad2345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>785e3ad6-514f-44d2-ad56-7737128446d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Quý khách vui lòng nhập mã OTP</value>
      <webElementGuid>62b68e3c-48ca-4884-8a53-169f0277b9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-length-message</name>
      <type>Main</type>
      <value>OTP không hợp lệ</value>
      <webElementGuid>f885d41e-2a15-445d-9d11-a161726e68f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otpvalue&quot;)</value>
      <webElementGuid>bd0ff332-b12d-4e7e-b0bd-6ac767053442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otpvalue']</value>
      <webElementGuid>fb4e7929-2a4e-4fec-a9c8-cc5a06d11f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='otpConfirm']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>c715fd51-510f-48c4-b367-879676231f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0071ce28-99d7-4dfb-a466-2d242665d3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otpvalue' and @id = 'otpvalue' and @placeholder = 'Nhập mã OTP']</value>
      <webElementGuid>9f0e0cf2-e00a-418c-928f-dc6f79eb959c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
