<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Thanh ton</name>
   <tag></tag>
   <elementGuidId>c3da8343-20c0-4bb9-87cd-b1ea4786d3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnConfirm > div.ubtn-inner > span.ubtn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnConfirm']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Thanh toán&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65ce9ae1-7c2b-4abf-971c-7551b5e88086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ubtn-text</value>
      <webElementGuid>86f1614a-14d9-4cdc-808b-dffa36b44c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh toán</value>
      <webElementGuid>e3447259-1ba7-45c9-8ec8-fb43b7cae6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnConfirm&quot;)/div[@class=&quot;ubtn-inner&quot;]/span[@class=&quot;ubtn-text&quot;]</value>
      <webElementGuid>919f2680-69bb-421a-bd19-de919d6480d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnConfirm']/div/span</value>
      <webElementGuid>7ab8a856-7c39-4638-a899-d47df429df48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/following::span[1]</value>
      <webElementGuid>96c9bc05-e5f7-4ccb-803c-df958af7801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xác thực OTP'])[3]/following::span[2]</value>
      <webElementGuid>f0093ed8-0111-47a0-af94-a5357a74a9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phát triển bởi VNPAY © 2025'])[1]/preceding::span[1]</value>
      <webElementGuid>711b8b09-9871-4a01-8af9-ad0b5c523b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hotrovnpay@vnpay.vn'])[1]/preceding::span[2]</value>
      <webElementGuid>7026706e-83ac-40fa-a1a8-4cd511e9e0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanh toán']/parent::*</value>
      <webElementGuid>14a772a9-64d5-41bf-abd0-5496ed6f6aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span</value>
      <webElementGuid>ae5d66d3-2fc3-4873-aefc-4f5189050db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thanh toán' or . = 'Thanh toán')]</value>
      <webElementGuid>13e812bc-5581-4d1b-a958-f3ee019a2322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
