<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ng   Tip tc</name>
   <tag></tag>
   <elementGuidId>0ef5043b-c201-4f01-b095-7c2649db735c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAgree > div.ubtn-inner > span.ubtn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAgree']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đồng ý &amp; Tiếp tục&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b82ce09-396f-474a-966f-9abec95f7234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ubtn-text</value>
      <webElementGuid>f8c4ae92-abb4-4afb-9058-0b71335f4c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đồng ý &amp; Tiếp tục</value>
      <webElementGuid>820be9aa-e9ed-4b23-9d9e-1f6949d7a764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAgree&quot;)/div[@class=&quot;ubtn-inner&quot;]/span[@class=&quot;ubtn-text&quot;]</value>
      <webElementGuid>ad7fb89c-d01f-4c62-b316-f94a9e5844a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnAgree']/div/span</value>
      <webElementGuid>77b52f14-fcbe-4993-b75a-e86d01021b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Không đồng ý'])[1]/following::span[1]</value>
      <webElementGuid>94aae03f-5e95-4ccd-bb78-31a3b86ad903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tại đây'])[1]/following::span[2]</value>
      <webElementGuid>67663ed5-f9d5-4285-a8f2-d57911577865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đồng ý &amp; Tiếp tục']/parent::*</value>
      <webElementGuid>c2693d55-8f96-43d2-9b16-be45f51a0e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[3]/div/div[2]/a/div/span</value>
      <webElementGuid>ebec5ad2-f670-40c4-9615-f462ab37d36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Đồng ý &amp; Tiếp tục' or . = 'Đồng ý &amp; Tiếp tục')]</value>
      <webElementGuid>9680c730-df94-465d-bbe9-e198f4819347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
