<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_n Hng_fa-regular fa-user</name>
   <tag></tag>
   <elementGuidId>51aa8e08-32b3-4cbb-a76f-ccf74462bde8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-regular.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/ul/li/p/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cb0196a9-fd6f-4772-9715-31db4163abe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-regular fa-user</value>
      <webElementGuid>04355981-b0a1-4432-85d4-2989bd766830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>320f68f4-7d81-49d5-b27c-f2c3b5a061e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;admin-header&quot;]/div[@class=&quot;admin-header-right&quot;]/ul[@class=&quot;flex-box account-actions&quot;]/li[@class=&quot;flex-box account-dropdown&quot;]/p[1]/i[@class=&quot;fa-regular fa-user&quot;]</value>
      <webElementGuid>536e4e8f-51b3-415f-8c6b-bd556de06b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/ul/li/p/i</value>
      <webElementGuid>377bee10-cc3e-40d1-8fb6-1e7eff28bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>ef12c2b3-b60e-456f-bd6f-b1947700b98f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
