<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_n Hng_fa-regular fa-user</name>
   <tag></tag>
   <elementGuidId>51aa8e08-32b3-4cbb-a76f-ccf74462bde8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-regular.fa-user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/ul/li/p/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bf52dd8d-7d0b-493a-9a94-1f29373a6f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-regular fa-user</value>
      <webElementGuid>21ee3ad0-b3ce-404f-9a0b-3055a763a9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72fb4ed2-3085-48cc-bfdb-70bdd6b2b251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;admin-header&quot;]/div[@class=&quot;admin-header-right&quot;]/ul[@class=&quot;flex-box account-actions&quot;]/li[@class=&quot;flex-box account-dropdown&quot;]/p[1]/i[@class=&quot;fa-regular fa-user&quot;]</value>
      <webElementGuid>42b1a709-0d3e-441b-9f5d-412d857814d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/ul/li/p/i</value>
      <webElementGuid>567b2c9f-1dc7-4432-933b-924963a22653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>1f1eb568-6464-4f78-8460-b5aa1af1ac61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
