<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chn Phng thc thanh ton_bankCode</name>
   <tag></tag>
   <elementGuidId>6c328b58-f6be-4157-9ba3-c31f2171c490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vnbankPaymentMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vnbankPaymentMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#vnbankPaymentMethod</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>220a3f0b-3b84-461e-b9cf-6f6650c667ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>067f5718-dc89-431e-9ed0-aa9ac96a782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bankCode</value>
      <webElementGuid>f2700100-a511-46fe-a10d-4e2a589fdf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vnbankPaymentMethod</value>
      <webElementGuid>348e3d58-0185-4e27-a733-d3de8704de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VNBANK</value>
      <webElementGuid>d7af8567-2629-4a90-a26c-222eedca54e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vnbankPaymentMethod&quot;)</value>
      <webElementGuid>f08950ef-b881-46bb-b68e-d73452d07ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vnbankPaymentMethod']</value>
      <webElementGuid>3d246e11-ea88-45ef-bc75-33cb2cc10462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createOrder']/div[2]/input[3]</value>
      <webElementGuid>d363fe45-2f27-4a16-b600-5a75a02fde70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>a59820a8-1871-4219-b2f2-f602715309c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'bankCode' and @id = 'vnbankPaymentMethod']</value>
      <webElementGuid>f3ce5aa1-fdd9-4ca7-833f-025e6b6f6d25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
