<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh Ton</name>
   <tag></tag>
   <elementGuidId>9f706fb1-be25-4707-ba5c-f6f568afae05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cart-order__payment-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Thanh Toán&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d96b12f-687e-43e2-b9d2-4329ba2c3608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-order__payment-btn</value>
      <webElementGuid>d93b37de-a9f2-46c6-86a8-25715409717f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh Toán</value>
      <webElementGuid>b2e75a82-36f4-4c75-a465-9227abb80e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cart-popup&quot;]/div[@class=&quot;cart-popup__content&quot;]/div[@class=&quot;cart-items&quot;]/div[@class=&quot;cart-order&quot;]/div[@class=&quot;cart-order__footer&quot;]/button[@class=&quot;cart-order__payment-btn&quot;]</value>
      <webElementGuid>e76cc379-6b15-4cab-be0c-35a823708992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>1d7df04c-1111-40a9-b073-b95de7f8d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa Đơn Hàng'])[1]/following::button[1]</value>
      <webElementGuid>fef72ab6-734a-4774-84aa-b8654ca5a2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanh Toán']/parent::*</value>
      <webElementGuid>cd416760-7da9-46f6-ae34-e1f23b810b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4f6d7919-25f5-4bf4-aed0-756f7fab44b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Thanh Toán' or . = 'Thanh Toán')]</value>
      <webElementGuid>cd71eba9-b1d5-420f-aa06-b399db62a17d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
