<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xa n Hng</name>
   <tag></tag>
   <elementGuidId>9c050890-4f0b-42ca-bfd7-27bee317cc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cart-order__remove-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Xóa Đơn Hàng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a96b4871-aeb3-45b8-8ca1-833273603709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-order__remove-btn</value>
      <webElementGuid>b2b69068-c896-4fc8-b648-85084406ee02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa Đơn Hàng</value>
      <webElementGuid>02459c4b-98f4-4375-8673-d138b048fdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cart-popup&quot;]/div[@class=&quot;cart-popup__content&quot;]/div[@class=&quot;cart-items&quot;]/div[@class=&quot;cart-order&quot;]/div[@class=&quot;cart-order__footer&quot;]/button[@class=&quot;cart-order__remove-btn&quot;]</value>
      <webElementGuid>6ee3d59f-1b41-4e52-b56d-657e3ef55b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>3a1f7556-29dc-4361-9008-836a57388039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giỏ Hàng'])[1]/following::button[1]</value>
      <webElementGuid>5c45a1b2-604e-41c6-a305-6a3c500a963e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh Toán'])[1]/preceding::button[1]</value>
      <webElementGuid>aaee7dd7-2704-4ae3-9fe3-02dfdf98bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xóa Đơn Hàng']/parent::*</value>
      <webElementGuid>86f7402d-520d-40ac-8980-48865c265283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>841e9a25-3151-460d-9889-6c6482b4a627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Xóa Đơn Hàng' or . = 'Xóa Đơn Hàng')]</value>
      <webElementGuid>162476f8-d79e-4218-815d-29371fd2b164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div[3]/div[2]/button</value>
      <webElementGuid>aa0ff7ac-75ff-4925-9ca5-ac092cd33ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh Toán'])[1]/following::button[1]</value>
      <webElementGuid>756fda6e-707e-4471-b2a9-827459a51992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh Toán'])[2]/preceding::button[1]</value>
      <webElementGuid>886c9331-ed3c-4b31-a98d-3c1e7f6e134d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>25e284fd-a772-449d-8efe-93ce1aeb65bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
