<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Trng Thi  hon thnh</name>
   <tag></tag>
   <elementGuidId>1e228564-95f9-412c-8012-287be4930301</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.cart-order__status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Trạng Thái: Đã hoàn thành&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a08e6005-a526-42df-98e8-e3dc56adfc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-order__status</value>
      <webElementGuid>549ebc6b-870b-43e6-b987-e57fb90783e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trạng Thái: Đã hoàn thành</value>
      <webElementGuid>a101567a-8b1a-4525-8f73-7b54fc453a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cart-popup&quot;]/div[@class=&quot;cart-popup__content&quot;]/div[@class=&quot;cart-items&quot;]/div[@class=&quot;cart-order&quot;]/p[@class=&quot;cart-order__status&quot;]</value>
      <webElementGuid>1e9c8c4b-f31f-4f0d-9975-18479ad0a65b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/div/p</value>
      <webElementGuid>9c163f67-de20-4026-a874-5d5025903946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giỏ Hàng'])[1]/following::p[1]</value>
      <webElementGuid>018d0de2-ba03-4a22-877d-e10ab4e8261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trạng Thái:']/parent::*</value>
      <webElementGuid>426ccfe2-d050-4e73-a9e7-4c20194d6a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/p</value>
      <webElementGuid>975c8c6c-b3fe-4b6c-83e8-8781201945f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Trạng Thái: Đã hoàn thành' or . = 'Trạng Thái: Đã hoàn thành')]</value>
      <webElementGuid>d0f42e39-1d60-4138-b3b6-91c7c803b19d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
