<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Th ni a_card_number_mask</name>
   <tag></tag>
   <elementGuidId>7f991118-45f0-4c8a-b363-a8e3a1bfbe71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number_mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number_mask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Số thẻ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1a9d99a-e0eb-437f-b5c9-30b47d8d64e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>digits</value>
      <webElementGuid>d3917e76-59ef-4574-aaeb-5aabdc7c4553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input-label-change input-has-clear</value>
      <webElementGuid>a6279a70-b5e2-40b2-bf75-e92937d72086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập số thẻ
</value>
      <webElementGuid>6197ad96-06b6-4ade-8f39-52c60b1fb929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>f61a8759-c22b-4fa8-a732-a0f0b9ab9f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>74a38b9f-1627-400c-8616-89cbabe2827b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number_mask</value>
      <webElementGuid>7eb25cb2-c53e-4685-89bc-3c657c1f072c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number_mask</value>
      <webElementGuid>3ba0cbe6-7b43-471f-b97c-bac83faa43a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a0c0b068-452b-4af2-9409-44979cf9d9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>433c1baf-21b1-44e1-9845-4afab78971af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>dba6f589-6ec3-41c9-95f3-ac039e3d21d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-bincode</name>
      <type>Main</type>
      <value>970419</value>
      <webElementGuid>76264b27-d982-464c-bce6-1654c402fecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>Quý khách vui lòng nhập Số thẻ</value>
      <webElementGuid>a11a62bb-3dfd-4bed-b4cd-06fa1687ac4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-length-message</name>
      <type>Main</type>
      <value>Số thẻ không hợp lệ</value>
      <webElementGuid>8882cdde-ed87-41d1-9709-ef9ddd443419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-bincode-message</name>
      <type>Main</type>
      <value>Thông tin số thẻ chưa hợp lệ, quý khách vui lòng kiểm tra lại</value>
      <webElementGuid>4d45a713-17a5-4205-8f05-69b2535c4938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>#err-card</value>
      <webElementGuid>2b83331c-3ac1-4106-8d65-e6dd5db5b55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number_mask&quot;)</value>
      <webElementGuid>5163c6c6-bbc4-46f5-b8ab-15e5633e3bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number_mask']</value>
      <webElementGuid>78282dd2-3d50-4510-821f-e179bc999bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cardVerify']/div/div[2]/div/div/div/div/div/label/input</value>
      <webElementGuid>b48af2dd-937b-48a9-82d1-ec52b4cffa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6873f291-139f-45af-bdfb-ca09d30afa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'digits' and @placeholder = 'Nhập số thẻ
' and @id = 'card_number_mask' and @name = 'card_number_mask']</value>
      <webElementGuid>bb70b52e-4b2e-43dd-a7e2-bcc45041f5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
