<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Th ni a v ti khon ngn hng_list-bank-item-inner</name>
   <tag></tag>
   <elementGuidId>36795529-9502-46cb-ada2-424f42087aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NCB > div.list-bank-item-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='NCB']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NCB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d600d9e4-23d3-4885-946a-1d2383ff0953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-bank-item-inner</value>
      <webElementGuid>ebc30d08-e548-4341-9a6e-1d58e8b34e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NCB&quot;)/div[@class=&quot;list-bank-item-inner&quot;]</value>
      <webElementGuid>3a8aef0a-c669-4dde-90df-81f5772669d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='NCB']/div</value>
      <webElementGuid>0089af9f-269a-4c27-8502-6bcebe03759a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/button/div</value>
      <webElementGuid>913ccbfc-4ffe-49e7-9324-6adbe9b3eeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
